import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { AdminShell, AdminTableEmpty } from "@/components/admin-shell";
import { AdminDeleteButton } from "@/components/admin-delete-button";
import { deleteNotice } from "@/app/admin/admin-actions";
import { ContentFeedback } from "@/components/admin-content-forms";

export default async function AdminNoticesPage({ searchParams }: { searchParams: Promise<{ q?: string; category?: string; status?: string; pinned?: string; archived?: string; result?: string; error?: string }> }) {
  const filters = await searchParams;
  const notices = await prisma.notice.findMany({ where: { type: "NOTICE", ...(filters.q ? { OR: [{ title: { contains: filters.q, mode: "insensitive" } }, { description: { contains: filters.q, mode: "insensitive" } }, { content: { contains: filters.q, mode: "insensitive" } }] } : {}), ...(filters.category ? { category: filters.category } : {}), ...(filters.status === "PUBLISHED" || filters.status === "DRAFT" || filters.status === "UNPUBLISHED" ? { status: filters.status } : {}), ...(filters.pinned === "true" ? { isPinned: true } : {}), ...(filters.archived === "true" ? { isArchived: true } : {}) }, orderBy: { createdAt: "desc" } });
  return <AdminShell title="Notices" description="Create, review, publish, pin, archive, and remove school notices."><ContentFeedback status={filters.result} error={filters.error} /><form className="admin-filter-form" action="/admin/notices"><input name="q" placeholder="Search notices" defaultValue={filters.q} /><input name="category" placeholder="Category" defaultValue={filters.category} /><select name="status" defaultValue={filters.status ?? ""}><option value="">All statuses</option><option value="PUBLISHED">Published</option><option value="DRAFT">Draft</option><option value="UNPUBLISHED">Unpublished</option></select><label><input type="checkbox" name="pinned" value="true" defaultChecked={filters.pinned === "true"} /> Pinned</label><label><input type="checkbox" name="archived" value="true" defaultChecked={filters.archived === "true"} /> Archived</label><button className="button button-dark" type="submit">Filter</button><Link className="button button-outline-dark" href="/admin/notices">Clear</Link></form><div className="admin-toolbar"><p>{notices.length} matching notices</p><Link className="button button-dark" href="/admin/notices/new">Add notice <span aria-hidden="true">+</span></Link></div>{notices.length === 0 ? <AdminTableEmpty message="No notices have been added. Add school-provided content when it is ready." /> : <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Notice</th><th>Category</th><th>Status</th><th>Flags</th><th>Actions</th></tr></thead><tbody>{notices.map((notice) => <tr key={notice.id}><td><strong>{notice.title}</strong><small>{notice.publishDate?.toLocaleDateString() ?? "No date set"}</small></td><td>{notice.category}</td><td><span className={`admin-status ${notice.status.toLowerCase()}`}>{notice.status}</span></td><td>{notice.isPinned ? "Pinned" : ""} {notice.isArchived ? "Archived" : ""}</td><td><div className="admin-row-actions"><Link href={`/admin/notices/${notice.id}/edit`}>Edit</Link><AdminDeleteButton action={deleteNotice} id={notice.id} label={notice.title} /></div></td></tr>)}</tbody></table></div>}</AdminShell>;
}
