import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { AdminShell, AdminTableEmpty } from "@/components/admin-shell";
import { AdminDeleteButton } from "@/components/admin-delete-button";
import { deleteEvent } from "@/app/admin/admin-actions";
import { ContentFeedback } from "@/components/admin-content-forms";

export default async function AdminEventsPage({ searchParams }: { searchParams: Promise<{ q?: string; category?: string; status?: string; publication?: string; featured?: string; result?: string; error?: string }> }) {
  const filters = await searchParams;
  const events = await prisma.event.findMany({ where: { ...(filters.q ? { OR: [{ title: { contains: filters.q, mode: "insensitive" } }, { description: { contains: filters.q, mode: "insensitive" } }, { venue: { contains: filters.q, mode: "insensitive" } }] } : {}), ...(filters.category ? { category: filters.category } : {}), ...(filters.status === "UPCOMING" || filters.status === "PAST" ? { status: filters.status } : {}), ...(filters.publication === "PUBLISHED" || filters.publication === "DRAFT" || filters.publication === "UNPUBLISHED" ? { publication: filters.publication } : {}), ...(filters.featured === "true" ? { isFeatured: true } : {}) }, orderBy: [{ eventDate: "asc" }, { createdAt: "desc" }] });
  return <AdminShell title="Events" description="Create, review, publish, and remove school events."><ContentFeedback status={filters.result} error={filters.error} /><form className="admin-filter-form" action="/admin/events"><input name="q" placeholder="Search events" defaultValue={filters.q} /><input name="category" placeholder="Category" defaultValue={filters.category} /><select name="status" defaultValue={filters.status ?? ""}><option value="">Upcoming and past</option><option value="UPCOMING">Upcoming</option><option value="PAST">Past</option></select><select name="publication" defaultValue={filters.publication ?? ""}><option value="">All publishing states</option><option value="PUBLISHED">Published</option><option value="DRAFT">Draft</option><option value="UNPUBLISHED">Unpublished</option></select><label><input type="checkbox" name="featured" value="true" defaultChecked={filters.featured === "true"} /> Featured</label><button className="button button-dark" type="submit">Search / filter</button><Link className="button button-outline-dark" href="/admin/events">Clear</Link></form><div className="admin-toolbar"><p>{events.length} matching events</p><Link className="button button-dark" href="/admin/events/new">Add event <span aria-hidden="true">+</span></Link></div>{events.length === 0 ? <AdminTableEmpty message="No events have been added. Add school-provided content when it is ready." /> : <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Event</th><th>Category</th><th>Date / venue</th><th>Timing</th><th>Publishing</th><th>Actions</th></tr></thead><tbody>{events.map((event) => <tr key={event.id}><td><strong>{event.title}</strong>{event.isFeatured && <small>Featured</small>}</td><td>{event.category}</td><td><small>{event.eventDate?.toLocaleDateString() ?? "Date not set"} · {event.venue ?? "Venue not set"}</small></td><td>{event.status}</td><td><span className={`admin-status ${event.publication.toLowerCase()}`}>{event.publication}</span></td><td><div className="admin-row-actions"><Link href={`/admin/events/${event.id}/edit`}>Edit</Link><AdminDeleteButton action={deleteEvent} id={event.id} label={event.title} /></div></td></tr>)}</tbody></table></div>}</AdminShell>;
}
