import Link from "next/link";
import { SiteHeader } from "@/components/site-header";
import { AcademicSection, ContactSection, EventsSection, GallerySection, NoticesSection, SchoolLifeSection, SiteFooter } from "@/components/home-sections";
import { homeContent, schoolContent } from "@/content/home-content";
import { prisma } from "@/lib/prisma";

export default async function Home() {
  const [settings, admissions] = await Promise.all([
    prisma.schoolSetting.findUnique({ where: { id: "school" }, select: { schoolName: true, aboutSchool: true, principalName: true, principalDesignation: true, principalMessage: true, principalPhotoUrl: true, principalPhotoAlt: true } }),
    prisma.admissionSetting.findUnique({ where: { id: "admissions" } }),
  ]);
  const schoolName = settings?.schoolName || "St. Thomas English School, Ruabandha, Bhilai.";
  const aboutSchool = settings?.aboutSchool || homeContent.about.description;
  const principalMessage = settings?.principalMessage?.split("\n\n").find((paragraph) => paragraph.trim().length > 40) || homeContent.principal.description;
  return <div id="top"><SiteHeader /><main>
    <section className="hero-section"><div className="hero-image" aria-hidden="true" /><div className="container hero-content"><p className="eyebrow light">{homeContent.hero.eyebrow}</p><h1>{homeContent.hero.title}</h1><p className="hero-intro">{homeContent.hero.description}</p><div className="hero-actions"><a className="button button-light" href="#about">Explore our school <span aria-hidden="true">↗</span></a><a className="button button-quiet" href="#admissions">Admissions <span aria-hidden="true">↗</span></a></div></div><div className="hero-note"><span>01</span><span className="hero-note-line" /><span>Learning beyond the classroom</span></div></section>
    <section className="quick-links" aria-label="Explore St. Thomas English School, Ruabandha, Bhilai."><div className="container quick-links-grid"><a className="quick-link" href="#admissions"><span className="quick-number">01</span><span><strong>Admissions</strong><small>Information to be updated</small></span><span className="quick-arrow" aria-hidden="true">→</span></a><a className="quick-link" href="#events"><span className="quick-number">02</span><span><strong>School calendar</strong><small>Sample dates to be updated</small></span><span className="quick-arrow" aria-hidden="true">↗</span></a><a className="quick-link" href="#portal"><span className="quick-number">03</span><span><strong>Parent portal</strong><small>Details to be updated</small></span><span className="quick-arrow" aria-hidden="true">↗</span></a></div></section>
    <section className="intro-section container" id="about"><div className="intro-label"><span className="eyebrow">{homeContent.about.eyebrow}</span><span className="vertical-rule" /></div><div className="intro-copy"><h2>{schoolName}</h2>{aboutSchool.split("\n\n").map((paragraph, index) => <p key={`${index}-${paragraph}`}>{paragraph}</p>)}<a className="text-link" href="/about">Read more about our school <span aria-hidden="true">↗</span></a></div><div className="intro-art" aria-hidden="true"><span>ST</span><small>Learn · Lead · Serve</small></div></section>
    <section className="welcome-section"><div className="container welcome-grid"><div className="welcome-photo" role="img" aria-label={settings?.principalPhotoUrl ? settings.principalPhotoAlt || `${settings.principalName || homeContent.principal.name} photo` : "School learning image placeholder"} style={settings?.principalPhotoUrl ? { backgroundImage: `url(${settings.principalPhotoUrl})`, backgroundPosition: "center", backgroundSize: "cover" } : undefined} /><div className="welcome-copy"><p className="eyebrow">{homeContent.principal.eyebrow}</p><h2>A school is built<br />on <em>relationships.</em></h2><p>{principalMessage}</p><a className="text-link" href="/about/principal-message">Read the Principal&apos;s Desk <span aria-hidden="true">↗</span></a><div className="signature"><span className="signature-mark">ST</span><span><strong>{settings?.principalName || homeContent.principal.name}</strong><small>{settings?.principalDesignation || schoolContent.principalDesignation}</small></span></div></div></div></section>
    <AcademicSection /><SchoolLifeSection /><NoticesSection /><EventsSection /><GallerySection />
    <section className="admissions-section" id="admissions"><div className="container admissions-inner"><p className="eyebrow">{homeContent.admissions.eyebrow}</p><h2>{admissions?.isPublished && admissions.headline ? admissions.headline : <>Admissions<br /><em>information.</em></>}</h2><p>{admissions?.isPublished && admissions.introduction ? admissions.introduction : "Admission information will be provided by the school."}</p>{admissions?.isPublished && Array.isArray(admissions.availableClasses) && admissions.availableClasses.length > 0 && <div className="admission-details"><span><strong>Available classes</strong>{admissions.availableClasses.filter((item): item is string => typeof item === "string").join(", ")}</span></div>}<div className="admission-actions"><Link className="button button-dark" href="/admissions">Admission information <span aria-hidden="true">↗</span></Link><Link className="button button-outline-dark" href="/admissions#enquiry">Submit an enquiry <span aria-hidden="true">↗</span></Link></div></div></section>
    <ContactSection />
  </main><SiteFooter /></div>;
}
