"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";
import { isSafeMediaReference } from "@/lib/media-validation";
import { removeReplacedMedia, removeUnreferencedGalleryMedia } from "@/lib/media-cleanup";

async function admin() { if (!(await auth())?.user) redirect("/admin/login"); }
const s = (v: FormDataEntryValue | null) => typeof v === "string" ? v.trim() : "";
const opt = (v: FormDataEntryValue | null) => s(v) || null;
const date = (v: FormDataEntryValue | null) => { const value = s(v); if (!value) return null; const d = new Date(value); return Number.isNaN(d.getTime()) ? null : d; };
const slug = (v: string) => v.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");

export async function createGalleryAlbum(f: FormData) { await admin(); const title = s(f.get("title")); const coverImage = opt(f.get("coverImage")); const coverImageKey = opt(f.get("coverImageKey")); if (!title) redirect("/admin/gallery/new?error=required"); if (!isSafeMediaReference(coverImage, coverImageKey) || (s(f.get("coverImageAlt")).length > 240)) redirect("/admin/gallery/new?error=invalid"); try { const album = await prisma.galleryAlbum.create({ data: { title, slug: slug(s(f.get("slug")) || title), category: s(f.get("category")) || "Campus", description: opt(f.get("description")), albumDate: date(f.get("albumDate")), coverImage, coverImageKey, coverImageAlt: opt(f.get("coverImageAlt")), eventId: opt(f.get("eventId")), status: f.get("published") === "on" ? "PUBLISHED" : "DRAFT" } }); revalidatePath("/admin/gallery"); revalidatePath("/gallery"); redirect(`/admin/gallery/${album.id}?result=created`); } catch (error) { if (typeof error === "object" && error !== null && "code" in error && error.code === "P2002") redirect("/admin/gallery/new?error=duplicate-slug"); throw error; } }
export async function updateGalleryAlbum(f: FormData) { await admin(); const id = s(f.get("id")); const title = s(f.get("title")); const coverImage = opt(f.get("coverImage")); const coverImageKey = opt(f.get("coverImageKey")); if (!id || !title) redirect("/admin/gallery?error=required"); if (!isSafeMediaReference(coverImage, coverImageKey) || (s(f.get("coverImageAlt")).length > 240)) redirect(`/admin/gallery/${id}?error=invalid`); const existing = await prisma.galleryAlbum.findUnique({ where: { id }, select: { coverImageKey: true } }); try { await prisma.galleryAlbum.update({ where: { id }, data: { title, slug: slug(s(f.get("slug")) || title), category: s(f.get("category")) || "Campus", description: opt(f.get("description")), albumDate: date(f.get("albumDate")), coverImage, coverImageKey, coverImageAlt: opt(f.get("coverImageAlt")), eventId: opt(f.get("eventId")), status: f.get("published") === "on" ? "PUBLISHED" : "DRAFT" } }); } catch (error) { if (typeof error === "object" && error !== null && "code" in error && error.code === "P2002") redirect(`/admin/gallery/${id}?error=duplicate-slug`); throw error; } await removeUnreferencedGalleryMedia(existing?.coverImageKey && existing.coverImageKey !== coverImageKey ? existing.coverImageKey : null); revalidatePath("/admin/gallery"); revalidatePath(`/admin/gallery/${id}`); revalidatePath("/gallery"); redirect(`/admin/gallery/${id}?result=updated`); }
export async function deleteGalleryAlbum(f: FormData) { await admin(); const id = s(f.get("id")); if (id) { const existing = await prisma.galleryAlbum.findUnique({ where: { id }, select: { coverImageKey: true, photos: { select: { imageKey: true } } } }); await prisma.galleryAlbum.delete({ where: { id } }); await removeReplacedMedia(existing?.coverImageKey ?? null, null); for (const photo of existing?.photos ?? []) await removeReplacedMedia(photo.imageKey, null); } revalidatePath("/admin/gallery"); revalidatePath("/gallery"); redirect("/admin/gallery?result=deleted"); }
export async function updateEnquiryStatus(f: FormData) { await admin(); const id = s(f.get("id")); const status = s(f.get("status")); if (id && ["NEW", "CONTACTED", "IN_PROGRESS", "CLOSED"].includes(status)) await prisma.enquiry.update({ where: { id }, data: { status: status as "NEW" | "CONTACTED" | "IN_PROGRESS" | "CLOSED" } }); revalidatePath("/admin/enquiries"); }
export async function deleteEnquiry(f: FormData) { await admin(); const id = s(f.get("id")); if (id) await prisma.enquiry.delete({ where: { id } }); revalidatePath("/admin/enquiries"); }
export async function createDownload(f: FormData) { await admin(); const title = s(f.get("title")); if (!title) return; await prisma.download.create({ data: { title, description: opt(f.get("description")), category: s(f.get("category")) || "Other Documents", fileUrl: s(f.get("fileUrl")), fileName: opt(f.get("fileName")), fileType: opt(f.get("fileType")), fileSize: opt(f.get("fileSize")), status: f.get("published") === "on" ? "PUBLISHED" : "DRAFT", publishDate: date(f.get("publishDate")) } }); revalidatePath("/admin/downloads"); revalidatePath("/downloads"); redirect("/admin/downloads"); }
export async function updateDownload(f: FormData) { await admin(); const id = s(f.get("id")); const title = s(f.get("title")); if (!id || !title) return; await prisma.download.update({ where: { id }, data: { title, description: opt(f.get("description")), category: s(f.get("category")) || "Other Documents", fileUrl: s(f.get("fileUrl")), fileName: opt(f.get("fileName")), fileType: opt(f.get("fileType")), fileSize: opt(f.get("fileSize")), status: f.get("published") === "on" ? "PUBLISHED" : "DRAFT", publishDate: date(f.get("publishDate")) } }); revalidatePath("/admin/downloads"); revalidatePath("/downloads"); redirect("/admin/downloads"); }
export async function deleteDownload(f: FormData) { await admin(); const id = s(f.get("id")); if (id) await prisma.download.delete({ where: { id } }); revalidatePath("/admin/downloads"); revalidatePath("/downloads"); }
