import Link from "next/link";
import { AdminDeleteButton } from "@/components/admin-delete-button";
import { AdminShell, AdminTableEmpty } from "@/components/admin-shell";
import { EnquiryStatusForm, PhaseFourFeedback, removeEnquiry } from "@/components/phase-four-forms";
import { $Enums } from "@/generated/prisma/client";
import { prisma } from "@/lib/prisma";

export default async function AdmissionsEnquiriesPage({ searchParams }: { searchParams: Promise<{ q?: string; status?: string; from?: string; to?: string; result?: string; error?: string }> }) {
	const filters = await searchParams;
	const from = filters.from ? new Date(`${filters.from}T00:00:00`) : null;
	const to = filters.to ? new Date(`${filters.to}T23:59:59.999`) : null;
	const dateFilter = { ...(from && !Number.isNaN(from.getTime()) ? { gte: from } : {}), ...(to && !Number.isNaN(to.getTime()) ? { lte: to } : {}) };
	const statusFilter = filters.status === "NEW" || filters.status === "CLOSED" ? { status: filters.status as $Enums.EnquiryStatus } : filters.status === "CONTACTED" ? { status: { in: [$Enums.EnquiryStatus.CONTACTED, $Enums.EnquiryStatus.IN_PROGRESS] } } : {};
	const enquiries = await prisma.enquiry.findMany({ where: { ...(filters.q ? { OR: [{ applicantName: { contains: filters.q, mode: "insensitive" } }, { studentName: { contains: filters.q, mode: "insensitive" } }, { phone: { contains: filters.q } }, { email: { contains: filters.q, mode: "insensitive" } }, { message: { contains: filters.q, mode: "insensitive" } }] } : {}), ...statusFilter, ...(Object.keys(dateFilter).length ? { createdAt: dateFilter } : {}) }, orderBy: { createdAt: "desc" } });
	return <AdminShell title="Admission Enquiries" description="Private family enquiries. This information is visible only to authenticated administrators."><PhaseFourFeedback result={filters.result} error={filters.error} /><form className="admin-filter-form" action="/admin/admissions/enquiries"><input name="q" placeholder="Search name, email, phone or message" aria-label="Search enquiries" defaultValue={filters.q ?? ""} /><label>From<input name="from" type="date" defaultValue={filters.from ?? ""} /></label><label>To<input name="to" type="date" defaultValue={filters.to ?? ""} /></label><select name="status" aria-label="Filter by status" defaultValue={filters.status ?? ""}><option value="">All statuses</option><option value="NEW">New</option><option value="CONTACTED">Contacted</option><option value="CLOSED">Closed</option></select><button className="button button-dark">Search / filter</button><Link className="button button-outline-dark" href="/admin/admissions/enquiries">Clear</Link></form><div className="admin-toolbar"><p>{enquiries.length} enquiries</p></div>{enquiries.length ? <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Parent / guardian</th><th>Student</th><th>Contact</th><th>Class</th><th>Message</th><th>Received</th><th>Status</th><th>Delete</th></tr></thead><tbody>{enquiries.map((item) => <tr key={item.id}><td><strong>{item.applicantName}</strong></td><td>{item.studentName ?? "Not provided"}</td><td>{item.phone}{item.email && <><br />{item.email}</>}</td><td>{item.classApplyingFor ?? "Not provided"}</td><td>{item.message}</td><td>{item.createdAt.toLocaleString()}</td><td><EnquiryStatusForm id={item.id} status={item.status} /></td><td><AdminDeleteButton action={removeEnquiry} id={item.id} label={`enquiry from ${item.applicantName}`} /></td></tr>)}</tbody></table></div> : <AdminTableEmpty message="No admission enquiries have been received." />}</AdminShell>;
}